### ISSUE TITLE
Install `@uniqys/cli` on node v12

### ISSUE THREAD

**Issue by odanado** [uniqys/UniqysKit#36]
### Type
bug report

### Description
node: v12.0.0
npm: 6.9.0

When I ran `npm install @uniqys/cli`, I got the following error.
```bash
$ npm install @uniqys/cli
.
.
.
fatal error: too many errors emitted, stopping now [-ferror-limit=]
7 warnings and 20 errors generated.
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/.anyenv/envs/nodenv/versions/12.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/user/.anyenv/envs/nodenv/versions/12.0.0/bin/node" "/Users/user/.anyenv/envs/nodenv/versions/12.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/sandbox/kit-node-12-sandbox/node_modules/@uniqys/cli/node_modules/leveldown
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN kit-node-12-sandbox@1.0.0 No description
npm WARN kit-node-12-sandbox@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@4.0.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

However, It was successful to install only `leveldown` .

```bash
$ npm install leveldown                                                                                                                                             1

> leveldown@5.1.0 install /Users/user/sandbox/kit-node-12-sandbox/node_modules/leveldown
> node-gyp-build

npm WARN kit-node-12-sandbox@1.0.0 No description
npm WARN kit-node-12-sandbox@1.0.0 No repository field.

+ leveldown@5.1.0
removed 399 packages, updated 1 package and audited 13 packages in 2.604s
found 0 vulnerabilities
````

**Comment by odanado** [comment]
It was successful to install `@uniqys/cli` using node v11.15.0 and npm 6.7.0.

**Comment by odanado** [comment]
> For node 12, you'll need leveldown@5.
https://github.com/Level/leveldown/issues/628
